### ISSUE TITLE
Error in Telegram handler

### ISSUE THREAD

**Issue by fargoss** [klen/graphite-beacon#127]
```
[E 160818 22:21:55 concurrent:129] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "graphite_beacon/handlers/telegram.py", line 70, in _respond_commands
        message = update["message"]["text"].encode("utf-8")
    KeyError: 'text'
```

**Comment by fried-sausage** [comment]
To anyone wiling to reproduce this bug: seems like simply editing your message will be enough: bot receives update but there is no 'message' field, hence the error.
