### ISSUE TITLE
Support numeric interval value or improve error message

### ISSUE THREAD

**Issue by ipmb** [klen/graphite-beacon#57]
Initially I incorrectly set `interval: 120`. The error message I encountered didn't tell me where the error in my config was which made troubleshooting difficult. It'd be nice to support integers (as seconds) or provide a more helpful traceback if somebody else makes the same mistake. Here's the traceback I received:

```
Traceback (most recent call last):
  File "/usr/local/bin/graphite-beacon", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/app.py", line 16, in run
    r = Reactor(**options.as_dict())
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/core.py", line 54, in __init__
    self.reinit(**options)
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/core.py", line 80, in reinit
    BaseAlert.get(self, **opts).start() for opts in self.options.get('alerts', []))
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/core.py", line 80, in <genexpr>
    BaseAlert.get(self, **opts).start() for opts in self.options.get('alerts', []))
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 45, in get
    return acls(reactor, **options)
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 62, in __init__
    raise ValueError("Invalid alert configuration: %s" % e)
ValueError: Invalid alert configuration: expected string or buffer
```

**Comment by klen** [comment]
Thank you for the feedback. Fixed in develop version.
