### ISSUE TITLE
Hipchat handler fails to send messages

### ISSUE THREAD

**Issue by nicolas-ginder** [klen/graphite-beacon#75]
I'm getting this when trying to integrate with Hipchat using 0.24.1

[E 150814 16:08:36 concurrent:122] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "/usr/lib/python2.6/site-packages/graphite_beacon/handlers/hipchat.py", line 43, in notify
        url=self.options.url, room=self.room, token=self.key),
    AttributeError: 'dict' object has no attribute 'url'

**Comment by kwinczek** [comment]
This fixes it:
https://github.com/akang31/graphite-beacon/commit/ed1172479388c302356af093f6dd855cab61f914
