### ISSUE TITLE
Question about including.

### ISSUE THREAD

**Issue by dinapappor** [klen/graphite-beacon#88]
I am trying to modularize my config and as such I want to break up different categories of alarms into different files.

How ever including does not seem to work (my understanding of it is probably wrong).

```
"alerts":[{"include": "alerts/bookings.json"}]
```

Yields a 

```
[E 151019 14:02:27 alerts:77] Alert's name should be defined and not empty.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 75, in __init__
        self.configure(**options)
      File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 230, in configure
        super(GraphiteAlert, self).configure(**options)
      File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 102, in configure
        raise AssertionError("Alert's name should be defined and not empty.")
    AssertionError: Alert's name should be defined and not empty.
Traceback (most recent call last):
  File "/usr/local/bin/graphite-beacon", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/app.py", line 16, in run
    r = Reactor(**options.as_dict())
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/core.py", line 59, in __init__
    self.reinit(**options)
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/core.py", line 88, in reinit
    BaseAlert.get(self, **opts).start() for opts in self.options.get('alerts', []))
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/core.py", line 88, in <genexpr>
    BaseAlert.get(self, **opts).start() for opts in self.options.get('alerts', []))
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 59, in get
    return acls(reactor, **options)
  File "/usr/local/lib/python2.7/site-packages/graphite_beacon/alerts.py", line 78, in __init__
    raise ValueError("Invalid alert configuration: %s" % e)
ValueError: Invalid alert configuration: Alert's name should be defined and not empty.
```
error.

the json file with the alert defined in it looks like this:

```
{"name": "name of alarm",
  "format": "short",
  "query": "query",
  "rules": ["critical: < 20", "warning: < 30" ] }
```

Any ideas on how to go about this?

**Comment by GarrettHeel** [comment]
You can include alerts from multiple files by putting your `include` clause at the root of the main configuration file and ensuring that the included files look like this:

```js
{
  "alerts": [
    {
      "name": "name of alarm",
      // ...
    }
  ]
}
```

I've updated the README to clarify this a little. Note that you'll need at least version `0.25.3` which fixes a bug with alerts in multiple config files.
